server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/contactDb?useSSL=false
   
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
   
app: 
  messages: 
    contactSaveSucc: Contact Saved
    contactsaveFail: Failed to save contact
    contactDelSucc: Contact Deleted
    contactDelFail: Failed to delete contact
